// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <MERRA2PluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(MERRA2,Engine)

// ****************************************************************************
//  Method: MERRA2EnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a MERRA2 writer.
//
//  Returns:    A MERRA2 writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
MERRA2EnginePluginInfo::GetWriter(void)
{
    return NULL;
}

